#!/usr/bin/python3.11
import sys
from colors import light_blue, light_red, red, green
from components import Parser, doRequest, Data

data = Data.get()

args = sys.argv[1:]

if len(args) == 0:
    print(red('No puede mandar una consulta vacia'))
    sys.exit(1)


parser = Parser()
parser.parse(list(args))

print(parser.argsr)

if '-i' in parser.argsr or '--init' in parser.argsr:
    print('Configuración del asistente')
    pass
    sys.exit(0)

if '-o' in parser.argsr:
    print('A continuación digite la',green("API_KEY"))
    token = input(green('TOKEN:'))
    sys.exit(0)


promp = parser.argsr['prompt']
#if len(promp) > 1:
#    response = doRequest(promp)
#    print(light_blue('TU:'),promp)
#    print(light_red(data['NAME']+':'),response.text)